name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image for Testing
        run: docker build --target test --tag todo-app:test .

      - name: Run Docker image for Testing
        run: docker run --env-file .env.test todo-app:test